### PR TITLE
Json

### PR DESCRIPTION
**Pull request by martyall**
- adds a json dump for r1cs, witness, input files
- integrates with arkworks-bridge (build for this project)
- use arkworks-bridge on ci instead of libsnark

### CODE REVIEW

**Comment by martyall** [comment]
Here are the benchmarking results (local)

### Keccak
```
benchmarking keccak800/keccak800-elaborate
time                 652.3 ms   (268.0 ms .. 1.152 s)
                     0.914 R²   (0.886 R² .. 1.000 R²)
mean                 364.2 ms   (264.5 ms .. 513.2 ms)
std dev              140.4 ms   (1.343 ms .. 172.6 ms)
variance introduced by outliers: 74% (severely inflated)

benchmarking keccak800/keccak800-constraints
time                 1.612 s    (1.211 s .. 1.914 s)
                     0.990 R²   (0.987 R² .. 1.000 R²)
mean                 1.629 s    (1.532 s .. 1.679 s)
std dev              97.32 ms   (65.03 ms .. 115.3 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking keccak800/keccak800-simplify
time                 5.993 s    (437.7 ms .. 9.123 s)
                     0.897 R²   (0.715 R² .. 1.000 R²)
mean                 6.194 s    (5.074 s .. 6.853 s)
std dev              1.140 s    (820.8 ms .. 1.370 s)
variance introduced by outliers: 47% (moderately inflated)

benchmarking keccak800/keccak800-r1cs
time                 5.459 s    (967.7 ms .. 9.087 s)
                     0.928 R²   (0.754 R² .. 1.000 R²)
mean                 7.370 s    (6.307 s .. 8.434 s)
std dev              1.254 s    (977.7 ms .. 1.479 s)
variance introduced by outliers: 47% (moderately inflated)

benchmarking keccak800/keccak800-witgen
time                 41.85 s    (30.38 s .. 55.61 s)
                     0.988 R²   (0.975 R² .. 1.000 R²)
mean                 43.06 s    (40.48 s .. 44.35 s)
std dev              2.630 s    (2.206 s .. 2.980 s)
variance introduced by outliers: 19% (moderately inflated)

benchmarking keccak800/keccak800-keygen
time                 14.90 s    (7.773 s .. 25.27 s)
                     0.949 R²   (0.877 R² .. 1.000 R²)
mean                 15.66 s    (13.35 s .. 17.24 s)
std dev              2.284 s    (1.101 s .. 2.943 s)
variance introduced by outliers: 24% (moderately inflated)

benchmarking keccak800/keccak800-verif
time                 64.66 s    (45.01 s .. 90.20 s)
                     0.976 R²   (0.969 R² .. 1.000 R²)
mean                 51.32 s    (47.13 s .. 57.40 s)
std dev              6.573 s    (1.728 s .. 8.370 s)
variance introduced by outliers: 24% (moderately inflated)

benchmarking keccak800/keccak800-full
time                 44.05 s    (40.93 s .. 46.12 s)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 42.20 s    (40.39 s .. 43.03 s)
std dev              1.781 s    (11.35 ms .. 2.278 s)
variance introduced by outliers: 19% (moderately inflated)

```

### map-list
```
benchmarking map-list/map-list-elaborate
time                 12.77 ms   (12.45 ms .. 13.08 ms)
                     0.995 R²   (0.989 R² .. 0.998 R²)
mean                 12.56 ms   (12.30 ms .. 12.81 ms)
std dev              611.3 μs   (464.1 μs .. 804.9 μs)
variance introduced by outliers: 21% (moderately inflated)

benchmarking map-list/map-list-constraints
time                 114.7 ms   (97.91 ms .. 123.5 ms)
                     0.987 R²   (0.975 R² .. 0.999 R²)
mean                 110.8 ms   (107.0 ms .. 113.9 ms)
std dev              6.343 ms   (5.224 ms .. 7.802 ms)
variance introduced by outliers: 12% (moderately inflated)

benchmarking map-list/map-list-simplify
time                 493.8 ms   (368.3 ms .. 785.9 ms)
                     0.959 R²   (0.937 R² .. 1.000 R²)
mean                 407.1 ms   (378.5 ms .. 457.3 ms)
std dev              48.35 ms   (2.200 ms .. 58.00 ms)
variance introduced by outliers: 23% (moderately inflated)

benchmarking map-list/map-list-r1cs
time                 764.1 ms   (345.9 ms .. 1.034 s)
                     0.968 R²   (0.889 R² .. 1.000 R²)
mean                 775.2 ms   (732.2 ms .. 840.5 ms)
std dev              61.59 ms   (21.42 ms .. 76.32 ms)
variance introduced by outliers: 21% (moderately inflated)

benchmarking map-list/map-list-witgen
time                 2.127 s    (2.068 s .. 2.209 s)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 2.080 s    (2.052 s .. 2.105 s)
std dev              29.53 ms   (22.74 ms .. 34.14 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking map-list/map-list-keygen
time                 988.4 ms   (NaN s .. 1.026 s)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 955.3 ms   (932.4 ms .. 969.5 ms)
std dev              22.29 ms   (7.164 ms .. 29.94 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking map-list/map-list-verif
time                 1.821 s    (1.782 s .. 1.878 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 1.807 s    (1.798 s .. 1.815 s)
std dev              10.57 ms   (5.446 ms .. 13.44 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking map-list/map-list-full
time                 2.058 s    (1.943 s .. 2.137 s)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 2.045 s    (2.025 s .. 2.067 s)
std dev              22.94 ms   (11.78 ms .. 32.25 ms)
variance introduced by outliers: 19% (moderately inflated)
```

### matrx-600
```
benchmarking fixed-matrix600/fixed-matrix600-elaborate
time                 256.5 ms   (47.96 ms .. NaN s)
                     0.873 R²   (0.817 R² .. 1.000 R²)
mean                 391.6 ms   (321.2 ms .. 430.5 ms)
std dev              67.64 ms   (24.25 ms .. 89.81 ms)
variance introduced by outliers: 47% (moderately inflated)

benchmarking fixed-matrix600/fixed-matrix600-constraints
time                 3.028 s    (2.848 s .. 3.279 s)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 2.863 s    (2.776 s .. 2.949 s)
std dev              101.9 ms   (76.82 ms .. 119.9 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking fixed-matrix600/fixed-matrix600-simplify
time                 12.17 s    (6.454 s .. 17.44 s)
                     0.973 R²   (0.904 R² .. 1.000 R²)
mean                 12.66 s    (11.05 s .. 13.82 s)
std dev              1.708 s    (998.9 ms .. 2.398 s)
variance introduced by outliers: 24% (moderately inflated)

benchmarking fixed-matrix600/fixed-matrix600-r1cs
time                 25.93 s    (19.01 s .. 41.80 s)
                     0.956 R²   (0.933 R² .. 1.000 R²)
mean                 17.29 s    (14.44 s .. 21.44 s)
std dev              4.354 s    (1.843 s .. 6.011 s)
variance introduced by outliers: 48% (moderately inflated)

benchmarking fixed-matrix600/fixed-matrix600-witgen
time                 15.89 s    (-56.77 ms .. 31.94 s)
                     0.831 R²   (0.663 R² .. 1.000 R²)
mean                 18.22 s    (14.68 s .. 22.35 s)
std dev              4.241 s    (2.905 s .. 5.193 s)
variance introduced by outliers: 48% (moderately inflated)

benchmarking fixed-matrix600/fixed-matrix600-keygen
time                 14.34 s    (6.195 s .. NaN s)
                     0.945 R²   (0.849 R² .. 1.000 R²)
mean                 15.05 s    (13.41 s .. 16.68 s)
std dev              1.965 s    (1.309 s .. 2.275 s)
variance introduced by outliers: 24% (moderately inflated)

```

**Comment by kejace** [comment]
```sh
> snarkl git:(json) ✗ cabal run criterion -- +RTS -N32 -RTS
```

## Keccak

```
benchmarking keccak800/keccak800-elaborate
time                 845.1 ms   (720.1 ms .. 939.9 ms)
                     0.998 R²   (0.991 R² .. NaN R²)
mean                 974.2 ms   (910.4 ms .. 1.037 s)
std dev              77.77 ms   (37.57 ms .. 92.38 ms)
variance introduced by outliers: 21% (moderately inflated)

benchmarking keccak800/keccak800-constraints
time                 3.496 s    (2.536 s .. 4.674 s)
                     0.987 R²   (0.958 R² .. 1.000 R²)
mean                 3.654 s    (3.420 s .. 3.788 s)
std dev              228.1 ms   (68.34 ms .. 309.9 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking keccak800/keccak800-simplify
time                 11.92 s    (11.58 s .. 12.70 s)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 11.36 s    (10.57 s .. 11.63 s)
std dev              525.3 ms   (6.688 ms .. 613.9 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking keccak800/keccak800-r1cs
time                 14.23 s    (12.04 s .. 15.96 s)
                     0.996 R²   (0.995 R² .. 1.000 R²)
mean                 14.34 s    (13.80 s .. 14.79 s)
std dev              541.6 ms   (355.0 ms .. 648.2 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking keccak800/keccak800-witgen
time                 83.68 s    (82.63 s .. 84.93 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 82.59 s    (81.95 s .. 82.91 s)
std dev              643.2 ms   (510.6 ms .. 741.5 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking keccak800/keccak800-keygen
time                 25.72 s    (23.55 s .. 28.07 s)
                     0.999 R²   (0.996 R² .. 1.000 R²)
mean                 25.94 s    (25.30 s .. 26.42 s)
std dev              663.5 ms   (316.6 ms .. 917.1 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking keccak800/keccak800-verif
time                 90.25 s    (86.28 s .. 92.61 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 91.57 s    (90.80 s .. 91.98 s)
std dev              730.4 ms   (130.5 ms .. 948.1 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking keccak800/keccak800-full
time                 84.98 s    (83.21 s .. 87.08 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 85.15 s    (84.62 s .. 85.34 s)
std dev              356.3 ms   (43.22 ms .. 450.0 ms)
variance introduced by outliers: 19% (moderately inflated)
```

## map-list

```
benchmarking map-list/map-list-elaborate
time                 37.95 ms   (31.29 ms .. 45.66 ms)
                     0.892 R²   (0.810 R² .. 0.962 R²)
mean                 33.10 ms   (29.34 ms .. 38.02 ms)
std dev              8.669 ms   (6.566 ms .. 10.78 ms)
variance introduced by outliers: 86% (severely inflated)

benchmarking map-list/map-list-constraints
time                 209.4 ms   (172.0 ms .. 241.4 ms)
                     0.988 R²   (0.973 R² .. 1.000 R²)
mean                 241.9 ms   (223.6 ms .. 268.3 ms)
std dev              28.93 ms   (20.28 ms .. 34.04 ms)
variance introduced by outliers: 31% (moderately inflated)

benchmarking map-list/map-list-simplify
time                 853.6 ms   (682.4 ms .. 1.227 s)
                     0.978 R²   (0.961 R² .. 1.000 R²)
mean                 811.4 ms   (755.4 ms .. 859.4 ms)
std dev              57.29 ms   (39.23 ms .. 69.30 ms)
variance introduced by outliers: 20% (moderately inflated)

benchmarking map-list/map-list-r1cs
time                 1.039 s    (1.008 s .. 1.071 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 1.163 s    (1.111 s .. 1.243 s)
std dev              76.19 ms   (26.90 ms .. 97.55 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking map-list/map-list-witgen
time                 3.994 s    (3.964 s .. 4.042 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 3.925 s    (3.868 s .. 3.950 s)
std dev              41.13 ms   (12.78 ms .. 56.06 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking map-list/map-list-keygen
time                 2.238 s    (2.026 s .. 2.587 s)
                     0.997 R²   (0.993 R² .. 1.000 R²)
mean                 2.213 s    (2.146 s .. 2.240 s)
std dev              48.72 ms   (17.04 ms .. 63.51 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking map-list/map-list-verif
time                 4.419 s    (4.076 s .. 4.655 s)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 4.375 s    (4.299 s .. 4.439 s)
std dev              79.34 ms   (40.10 ms .. 102.2 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking map-list/map-list-full
time                 3.806 s    (3.617 s .. 3.948 s)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 3.855 s    (3.821 s .. 3.881 s)
std dev              32.70 ms   (2.525 ms .. 40.32 ms)
variance introduced by outliers: 19% (moderately inflated)
```

## fixed-matrix600

```
benchmarking fixed-matrix600/fixed-matrix600-elaborate
time                 697.7 ms   (321.4 ms .. 1.196 s)
                     0.946 R²   (0.858 R² .. 1.000 R²)
mean                 779.2 ms   (709.8 ms .. 895.8 ms)
std dev              113.8 ms   (5.494 ms .. 143.2 ms)
variance introduced by outliers: 24% (moderately inflated)

benchmarking fixed-matrix600/fixed-matrix600-constraints
time                 6.444 s    (5.058 s .. 7.575 s)
                     0.995 R²   (0.981 R² .. 1.000 R²)
mean                 6.341 s    (6.189 s .. 6.583 s)
std dev              234.8 ms   (40.21 ms .. 303.3 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking fixed-matrix600/fixed-matrix600-simplify
time                 21.88 s    (21.73 s .. 22.58 s)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 21.32 s    (20.87 s .. 21.58 s)
std dev              422.8 ms   (150.8 ms .. 559.6 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking fixed-matrix600/fixed-matrix600-r1cs
time                 25.50 s    (24.79 s .. 26.08 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 25.77 s    (25.57 s .. 25.93 s)
std dev              197.5 ms   (127.7 ms .. 239.5 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking fixed-matrix600/fixed-matrix600-witgen
time                 27.80 s    (26.65 s .. 30.36 s)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 26.73 s    (26.41 s .. 27.28 s)
std dev              537.9 ms   (47.30 ms .. 688.9 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking fixed-matrix600/fixed-matrix600-keygen
time                 25.40 s    (24.20 s .. 27.05 s)
                     1.000 R²   (0.998 R² .. 1.000 R²)
mean                 25.30 s    (24.95 s .. 25.48 s)
std dev              327.0 ms   (97.71 ms .. 425.3 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking fixed-matrix600/fixed-matrix600-verif
time                 26.19 s    (24.97 s .. 27.04 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 26.95 s    (26.44 s .. 27.19 s)
std dev              372.3 ms   (117.3 ms .. 485.8 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking fixed-matrix600/fixed-matrix600-full
time                 29.23 s    (25.64 s .. 31.32 s)
                     0.998 R²   (0.995 R² .. 1.000 R²)
mean                 27.84 s    (26.69 s .. 28.34 s)
std dev              857.1 ms   (260.7 ms .. 1.152 s)
variance introduced by outliers: 19% (moderately inflated)
```

## input-matrix70

```
benchmarking input-matrix70/input-matrix70-elaborate
time                 1.320 s    (948.0 ms .. 1.677 s)
                     0.990 R²   (0.963 R² .. 1.000 R²)
mean                 1.447 s    (1.361 s .. 1.519 s)
std dev              95.07 ms   (44.00 ms .. 121.6 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking input-matrix70/input-matrix70-constraints
time                 6.428 s    (3.468 s .. 8.412 s)
                     0.977 R²   (0.920 R² .. 1.000 R²)
mean                 6.432 s    (6.122 s .. 6.908 s)
std dev              451.3 ms   (116.6 ms .. 579.4 ms)
variance introduced by outliers: 20% (moderately inflated)

benchmarking input-matrix70/input-matrix70-simplify
time                 16.75 s    (15.78 s .. 17.82 s)
                     1.000 R²   (0.998 R² .. 1.000 R²)
mean                 17.13 s    (16.85 s .. 17.58 s)
std dev              431.1 ms   (117.4 ms .. 565.8 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking input-matrix70/input-matrix70-r1cs
time                 23.25 s    (21.39 s .. 24.45 s)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 23.87 s    (23.40 s .. 24.68 s)
std dev              800.1 ms   (19.30 ms .. 1.051 s)
variance introduced by outliers: 19% (moderately inflated)

benchmarking input-matrix70/input-matrix70-witgen
time                 33.76 s    (33.35 s .. 34.51 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 33.32 s    (32.65 s .. 33.55 s)
std dev              449.7 ms   (14.24 ms .. 538.5 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking input-matrix70/input-matrix70-keygen
time                 50.50 s    (47.96 s .. 51.98 s)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 49.89 s    (49.29 s .. 50.24 s)
std dev              572.0 ms   (207.0 ms .. 731.6 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking input-matrix70/input-matrix70-verif
time                 42.95 s    (39.40 s .. 45.37 s)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 41.63 s    (39.91 s .. 42.30 s)
std dev              1.245 s    (61.43 ms .. 1.552 s)
variance introduced by outliers: 19% (moderately inflated)

benchmarking input-matrix70/input-matrix70-full
time                 34.59 s    (31.33 s .. 38.79 s)
                     0.998 R²   (0.994 R² .. 1.000 R²)
mean                 32.86 s    (31.77 s .. 33.89 s)
std dev              1.222 s    (826.9 ms .. 1.471 s)
variance introduced by outliers: 19% (moderately inflated)
```

**Comment by martyall** [comment]
@kejace Is this with libsnark or arkworks?

**Comment by kejace** [comment]
That’s this branch using 32/36 threads on threadripper.

**Comment by martyall** [comment]
@kejace Seems about 2-3x faster which is pretty cool. Whenever you get the chance, can you post the results from libsnark?

**Comment by martyall** [comment]
> @kejace Seems about 2-3x faster which is pretty cool. Whenever you get the chance, can you post the results from libsnark?

Actually, wait. I was comparing in the wrong order. Seems like it's slower than the laptop?

**Pull request merged**
